added evaluation testing
kylrth/procedure-generation pull request #12
Opened 2023-06-07 15:28 UTC by MkYacine

2023-06-07 18:03 UTC, kylrth requested changes

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        references=["\n".join(gold_ingredients) + "\n" + "\n".join(gold_instructions)],
I'm not sure if this matters for these evaluations, but I think I'd like to have `"\n\n"` between the ingredients and the steps, just to add some separation. Maybe it doesn't matter though?

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +    )
```suggestion
    log_text = "\n".join(
        "ingredient_comparison prompt:"
        + textwrap.indent("\n".join(msg.content for msg in messages), "  ")
        + f"ingredient_comparison response: {resp.generations[0][0].text} "
    )
```

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        logger.debug(f"FAIL- {log_text}\n\n\n")
It would be useful to log what exactly went wrong here. Can you log the exception?

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        logger.debug(f"FAIL- {log_text}\n\n\n")
I would also use logger.warning

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        matches = int(response.split()[2])
It might help me understand what this code is doing if you add a comment with a short example text

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +    )
These are all looking very similar, can we extract them to a logging function?

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +    except ValueError:
```suggestion
    if match is not None:
        out = int(match.group())
        logger.debug(f"{log_text}\n ingredient_consistency result: {out}\n\n\n")
    else:
```

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +    except ValueError:
Always better to avoid catching exceptions when you already know why the exception should happen. This way, exceptions that weren't what you expected can still surface, instead of disappearing silently

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        out = 42
why 42?

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        logger.debug(f"FAIL- {log_text}\n\n\n")
```suggestion
    if response.lower().startswith("true"):
        out = True
    elif response.lower().startswith("false"):
        out = False
    else:
        logger.debug(f"FAIL- {log_text}\nresponse did not start with 'true' or 'false'\n\n")
        return False
    logger.debug(f"{log_text}\n ingredient_consistency result: {out}\n\n\n")
```

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +    gold_instructions = "Instructions:\n" + "\n".join(gold["directions"])
This is not what the formatted recipe looks like when we get it from the model. When we get it from the model it usually comes with bullet points (`-`) and numbering. Will that affect some of the evaluations?

2023-06-07 18:03 UTC, kylrth commented on evaluation/eval.py
> +        ),
I think this is why my recommendation was to have each evaluation function take the arguments pre-parsed into their objects (e.g. the ingredients as `List[str]`). As the code stands now, you format these things into just the right shape for each evaluation function, and then often parse them out again inside the functions. In the future, if you ever change the format that an individual eval function expects, you'll have to remember to come here and change the formatting individually. I think it will be more maintainable to have each function (including this overall `evaluation` function) accept objects, like this:

```python
async def evaluation(title: str, gold_ings: List[str], gold_steps: List[str], pred_ings: List[str], pred_steps: List[str], logger: logging.Logger) -> Dict[str, Any]

def rouge(gold_ings: List[str], gold_steps: List[str], pred_ings: List[str], pred_steps: List[str]) -> float

def linguistic_correctness(ings: List[str], steps: List[str]) -> int

async def ingredient_comparison(gold_ings: List[str], pred_ings: List[str], logger: logging.Logger) -> float

async def ingredient_relevance(title: str, ings: List[str], logger: logging.Logger) -> float
```

2023-06-07 18:03 UTC, kylrth commented on run.py
> +    n_workers = min(n_workers, len(data))
Thanks :P

2023-06-07 18:03 UTC, kylrth commented on tests/evaluation/eval_eval.py
> +data_dir = "C:\\Users\\mk_ya\\Desktop\\dataset\\dataset"
make this an argparse flag, so we aren't committing any paths that are specific to our machines

2023-06-07 18:03 UTC, kylrth commented on tests/evaluation/eval_eval.py
> +import numpy as np
I think this file should be out in the main directory, since it's not technically a "test". It's more of an experiment, because it's not a binary pass/fail.

2023-06-07 18:03 UTC, kylrth commented on tests/evaluation/eval_eval.py
> +import asyncio
These imports aren't sorted right. Can you add `"I"` to the selected list of ruff linters in pyproject.toml and then make sure the imports are sorted?

2023-06-08 15:03 UTC, MkYacine commented on evaluation/eval.py
> +        logger.debug(f"FAIL- {log_text}\n\n\n")
We already know what exactly went wrong here: The extraction of the value from the LM output. 
The ValueError exception only occurs if "matches = int(response.split()[2])" fails.
By logging log_text, the log will have the LMs output, allowing us to see what went wrong

2023-06-08 15:23 UTC, MkYacine commented on evaluation/eval.py
> +    gold_instructions = "Instructions:\n" + "\n".join(gold["directions"])
In the following line I am formatting the model's output to have it be the same as the gold ingredients and instructions

2023-06-08 15:31 UTC, MkYacine commented on evaluation/eval.py
> +        out = 42
This will be removed
Also 42 is the meaning of life :P

2023-06-08 15:32 UTC, MkYacine commented on evaluation/eval.py
> +        logger.debug(f"FAIL- {log_text}\n\n\n")
This will be removed

2023-06-08 18:26 UTC, kylrth approved these changes

2023-06-08 18:26 UTC, merged