added formatting procedures pipeline
kylrth/procedure-generation pull request #19
Opened 2023-07-10 19:33 UTC by MkYacine

2023-07-10 20:27 UTC, kylrth requested changes
I would also recommend adding to the dataset/README.md file the instruction to use this script

2023-07-10 20:27 UTC, kylrth commented on dataset/prompt.json
> +}
Format this json yo

2023-07-10 20:27 UTC, kylrth commented on dataset/format_procedure.py
> +    if len(encoding.encode(context + temp)) < TOKEN__LIMIT:
Look here for how to count tokens for a chat model: https://github.com/kylrth/procedure-generation/blob/e5638fa0b825f5b94974499f61d63e1346b180b6/systems/model.py#L186

2023-07-10 20:27 UTC, kylrth commented on dataset/prompt.json
> +}
format this JSON my guy

2023-07-10 20:27 UTC, kylrth commented on dataset/format_procedure.py
> +        return ""
We should probably throw an error here, then catch the error in the main function, log it, and skip writing anything in the output file.

2023-07-10 20:27 UTC, kylrth commented on dataset/format_procedure.py
> +    encoding = tiktoken.encoding_for_model("gpt-4")
Let's not initialize the encoder every time the function is called; put this with the other global variables

2023-07-10 20:27 UTC, kylrth commented on dataset/format_procedure.py
> +            with Path.open(Path(des), "w") as file:
Do we need `encoding="utf-8"` here? I'm not sure how this works but I wanted to ask

2023-07-10 20:27 UTC, kylrth commented on dataset/format_procedure.py
> +    for filepath in glob.iglob(path + "/**/*.md", recursive=True):
```suggestion
    for idx, filepath in enumerate(glob.iglob(path + "/**/*.md", recursive=True)):
```

2023-07-11 14:56 UTC, MkYacine commented on dataset/format_procedure.py
> +            with Path.open(Path(des), "w") as file:
I think we do. Some of the procedures caused errors of unknown characters when I was trying to read their content.
Adding this solved that problem

2023-07-11 15:31 UTC, MkYacine commented on dataset/format_procedure.py
> +        return ""
I see wym, but with the changes I made to the code, the writing in the output file now is done in this method.
So there's no need to throw an error to the main method, I'm just logging the files that exceed the token limit.

2023-07-11 15:31 UTC, MkYacine commented on dataset/prompt.json
> +}
will do yo

2023-07-11 15:31 UTC, MkYacine commented on dataset/format_procedure.py
> +    encoding = tiktoken.encoding_for_model("gpt-4")
Got rid of the encoder all together, now using get_num_tokens()

2023-07-11 16:14 UTC, kylrth requested changes

2023-07-11 16:14 UTC, kylrth commented on dataset/format_procedure.py
> +        default="./data",
maybe we can make this `"./docs"` so that it works with where my script puts the files

2023-07-11 16:49 UTC, kylrth approved these changes

2023-07-11 16:49 UTC, merged